version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker 
    build:
      context: jenkins_data_save    
    ports:
      - "8080:8080"
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net

networks:
  net:

